name: Setup Node.js

description: Setup Node.js by using cache and npm

inputs:
  working-directory:
    description: working-directory of package-lock.json
    required: true

runs:
  # compositeが必須
  using: composite
  steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.working-directory }}/package.json
      - name: Install dependencies
        run: npm ci
        shell: bash
        working-directory: ${{ inputs.working-directory }}
